# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'DraftCap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DraftCap
  pod 'CropView'
  pod 'OpenCV', '4.1.0'
  pod 'BBMetalImage', '1.0.0'
  pod 'TOCropViewController', '2.5.0'
end
